# Generated by Django 6.0.3 on 2026-06-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0008_corevalue_missionvision_teammember_whychooseus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
        migrations.DeleteModel(
            name='MissionVision',
        ),
        migrations.DeleteModel(
            name='WhyChooseUs',
        ),
    ]
