# Generated by Django 6.0.3 on 2026-06-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0009_delete_corevalue_delete_missionvision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_rating', models.DecimalField(decimal_places=2, default=4.9, help_text='Rating of Platform (e.g. 4.9)', max_digits=3)),
                ('max_rating', models.IntegerField(default=5, help_text='Max rating scale (e.g. 5)')),
                ('reviews_count', models.CharField(default='200+', help_text='Number of customer reviews (e.g. 200+)', max_length=50)),
                ('whatsapp_number', models.CharField(default='+1234567890', help_text='WhatsApp phone number with country code', max_length=20)),
                ('whatsapp_text', models.CharField(default='Hello, I have a question about PickUp', help_text='Default message text for WhatsApp', max_length=255)),
                ('visit_title', models.CharField(default='VISIT US', max_length=100)),
                ('visit_text', models.TextField(default='123 Main Street, Suite 400, New York, NY 10001')),
                ('visit_icon', models.CharField(default='bi bi-geo-alt-fill', max_length=50)),
                ('call_title', models.CharField(default='CALL US', max_length=100)),
                ('call_text', models.TextField(default='+1 (555) 123-4567\n+1 (555) 765-4321')),
                ('call_icon', models.CharField(default='bi bi-telephone-fill', max_length=50)),
                ('email_title', models.CharField(default='EMAIL US', max_length=100)),
                ('email_text', models.TextField(default='support@pickup.com\nsales@pickup.com')),
                ('email_icon', models.CharField(default='bi bi-envelope-fill', max_length=50)),
                ('hours_title', models.CharField(default='STORE HOURS', max_length=100)),
                ('hours_text', models.TextField(default='Mon - Fri: 9:00 AM - 8:00 PM\nSat - Sun: 10:00 AM - 6:00 PM')),
                ('hours_icon', models.CharField(default='bi bi-clock-fill', max_length=50)),
                ('map_iframe', models.TextField(default='<iframe src="https://maps.google.com/maps?q=india&t=&z=5&ie=UTF8&iwloc=&output=embed" width="100%" height="150" style="border:0;" loading="lazy"></iframe>', help_text='Embed iframe code for Google Maps location')),
            ],
            options={
                'verbose_name': 'Contact Page Configuration',
                'verbose_name_plural': 'Contact Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
