# Generated by Django 6.0.6 on 2026-07-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0014_backfill_product_skus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('PickUp.product',),
        ),
    ]
