# Generated by Django 6.0.6 on 2026-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0015_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
