# Generated by Django 6.0.6 on 2026-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0018_alter_order_status_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(default='Anonymous User', max_length=100),
        ),
    ]
