# Generated by Django 6.0.6 on 2026-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0019_feedback_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='review_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
