# Generated by Django 6.0.6 on 2026-07-14 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickUp', '0020_feedback_review_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHelpQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_queries', to='PickUp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_help_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Help Query',
                'verbose_name_plural': 'Product Help Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
